development:
      host: localhost
      adapter: mysql
      database: tumhai_fedena
      port: 3306
      username: root
      password: mnbvcxz

test: &test
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: fedena

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: fedena
cucumber:
  <<: *test
